services:
- image:
    url: uiferniuergnu/idfsdjifr:iofrejgio
  name: tcuzysxdfwklv
  region: singapore
  runtime: image
  type: web
- image:
    url: denriufhruit/xcviodf:kcsdiorer
  name: mqnhbjdzgeul
  region: singapore
  runtime: image
  type: web
- image:
    url: dwefeer/xshdcbjs:jdeijiowf
  name: uewbxnglvfard
  region: singapore
  runtime: image
  type: web
- image:
    url: dewiodwe/xjuideuwi:djiowejio
  name: rfksovtep
  region: singapore
  runtime: image
  type: web
- image:
    url: nuyhuyumiu/jijuihu:ojijo
  name: fihnyvaczjqkrg
  region: singapore
  runtime: image
  type: web
- image:
    url: hudiewhdiwhiuer/jidowefjioew:jdiowejwe
  name: pcondetjqv
  region: singapore
  runtime: image
  type: web
- image:
    url: mdoiewjfoire/ioweidwoj:pkopqwop
  name: oejrubyihacf
  region: singapore
  runtime: image
  type: web
- image:
    url: niucfdjoireoie/zjixoasjoide:jifoerfjoier
  name: baqwmvfohkxy
  region: singapore
  runtime: image
  type: web
- image:
    url: miojiuygfytui/huihuw:ijoewdoiw
  name: cqlgwphfuna
  region: singapore
  runtime: image
  type: web
- image:
    url: ujidhueci/kioefgjit:kodwe
  name: mwrdiletkqjcosf
  region: singapore
  runtime: image
  type: web
